### ISSUE TITLE
Gif is too large (14mb)

### ISSUE THREAD

**Issue by LucaNerlich** [aemsites/audi#36]
- https://main--audi--aemsites.hlx.live/uk/web/en/used-cars/used-electric-and-hybrid
- https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B045A3AB6-9A70-40CE-A539-E57907459223%7D&file=used-electric-and-hybrid.docx&action=default&mobileredirect=true

![image](https://github.com/aemsites/audi/assets/5942270/cf8a78fc-017d-4cad-b6a4-547c26214424)

![image](https://github.com/aemsites/audi/assets/5942270/85f63a6b-6a33-46b1-bb11-de3575322988)

**Comment by amol-anand** [comment]
We should ask for a new image if they can give us one. 
However, I'm curious - is this bringing down page performance? If it is below the fold, it should not matter since it will be lazy loaded. Is something happening that should not happen here other than the fact that this image is too big for its own good?

**Comment by LucaNerlich** [comment]
Score is fine. As a mobile user, id just be a bit surprised, if a page loads such large assets.
